### PR TITLE
Create sitewide responsive grid system for re-use

### LINKED ISSUE #691: Improve responsiveness of playlists on home and user home
iPad portrait mode

Screenshot 2019-08-22 13 37 38
Screenshot 2019-08-22 13 37 26

### PR DESCRIPTION
**Pull request by ofsound**
Fixes #691

implemented on:
/home playlist area
/user playlist area
/user/playlists
/playlists
/users

A new SCSS file and class .responsive_grid that is added to UL>LI locations to display the items in a responsive 4>3>2 column layout

TODO
* [x] check out image sizes for thumbs ( in particular, /users images now showing at same size as playlists)
* [x] test both svg and jpgs
* [x] view & sort playlists on 2 column collapse, has an unwanted extra bottom margin

## "Ready For Review" checklist

These checklists are to help ensure the code review basics are covered. Consider removing to reduce noise.

* [ ] PR title accurately summarizes changes
* [ ] New tests were added for isolated methods or new endpoints
* [ ] I opened an issue for any logical followups
* [ ] If this fixes a bug, "Fixes #XXX" is either the very first or very last line of the description.

## Before code review *and after additional commits* during review.

* [ ] Update title and description to account for additional changes
* [ ] All tests green
* [ ] Booted up the branch locally, exercised any new code
* [ ] Percy changes are purposeful or explained
* [ ] Css changes are happy on mobile (via Percy is ok)

### CODE REVIEW

**Comment by sudara** [comment]
> view & sort playlists on 2 column collapse, has an unwanted extra bottom margin

@ofsound Is this something possible to fix? Looks like on mobile in particular, there's a lot of padding there.

**Comment by ofsound** [comment]
> > view & sort playlists on 2 column collapse, has an unwanted extra bottom margin
> 
> @ofsound Is this something possible to fix? Looks like on mobile in particular, there's a lot of padding there.

@sudara This should be fixed now.

The other issues that were unchecked, one I decided was correct, the sizing of 3 playlists on a user home page.

The other issue is part of a larger site wide question for Samo, concerning mobile gutters on most every page.

**Comment by sudara** [comment]
Re-running CI, failed to connect to selenium.

**Comment by sudara** [comment]
@ofsound Looks like https://percy.io/alonetone/alonetone/builds/2931272 is showing a padding change below playlists on mobile artist page

**Comment by ofsound** [comment]
> @ofsound Looks like https://percy.io/alonetone/alonetone/builds/2931272 is showing a padding change below playlists on mobile artist page

@sudara 

I think the percy padding discrepancy is due to percy only having 2 playlists showing on his homepage, where the layout code is written based on 4 playlists showing on the mobile home page.

**Pull request merged**
