### PR TITLE
Update Rubocop and set target Ruby version to 2.6

### PR DESCRIPTION
**Pull request by Manfred**

### CODE REVIEW

**Comment by Manfred** [comment]
Ah poo, CodeClimate doesn't support 2.6 yet.

**Comment by sudara** [comment]
> Thanks for writing in, and sorry about the lack of an update here. While we do plan on supporting Rubocop 0.62 in the near future, I don't yet have a hard ETA for that. I'll get back to you as soon as I have more info.

**Comment by Manfred** [comment]
Ah right, sorry, closing this for now.

**Comment by sudara** [comment]
Code climate support contacted and said 2.6 should work fine now: https://github.com/codeclimate/codeclimate-rubocop/pull/147

**Comment by efueger** [comment]
@sudara - we're close!  I did some testing and it looks like the new channel for **rubocop-0-62** isn't working as expected.

I've just [opened a PR on the plugin's repo](https://github.com/codeclimate/codeclimate-rubocop/issues/152) to have a dev take a closer look.

---

**rubocop-0-63**, **rubocop-0-60**, **rubocop-0-61** do currently support **Ruby 2.6**. (And **rubocop-0-62** will once we get that fixed.)

- For all of those, you'll need to add a channel specification in your .codeclimate.yml like this:

image

**Comment by efueger** [comment]
@sudara @Manfred - we've updated the **rubocop-0-62** channel.

- you'll need to add the extra line in your .codeclimate.yml to use the channel.

```
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-62
```

**Comment by sudara** [comment]
@efueger Thanks so much for the assist! Is there a way to tell codeclimate to use the latest rubocop channel available? Does it just key off the rubocop version in Gemfile by default? I couldn't find any documentation about it, and was wondering if there was a way not to hard code the version in the yml.

**Comment by efueger** [comment]
@sudara - We've discussed doing something more automatic than this (i.e., with the Gemfile), but right now it's hard coded. 

Let me know if anything else pops up. Happy to help 👍

**Comment by sudara** [comment]
Merging #430 instead.

**Pull request closed without merging**
