### PR TITLE
Implement new Playlist Player and Comment styles

### LINKED ISSUE #939: Implement normal track+comment layout changes
We ran into a problem on dark theme where it was hard to distinguish/visually separate tracks from each other when comments are attached. 

We resolved by simplifying (removing the triangle) and changing the layout a bit (comment fields are wider, avatar now overlays the comment vs. sits beside it). 

In figma: https://www.figma.com/file/YdjrVsNumbBsWVo82Wje2h6N/alonetone-white-theme?node-id=902%3A1373

image

### PR DESCRIPTION
**Pull request by ofsound**
Fixes #939, #938 

To Discuss with sudara:
* [ ] Rollover states on any of these new buttons
* [x] by You by Artist logic
* [x] add to favorites animation properly removed
* [x] what to do with the delete button on track edit
* [x] how to deal with groups of comments below a playlist track
* [x] checkboxes are different sizes, site wide change?
* [x] consider new placements for edit playlist and edit descriptions buttons
* [ ] color themes for external links

## "Ready For Review" checklist

These checklists are to help ensure the code review basics are covered. Consider removing to reduce noise.

* [x] PR title accurately summarizes changes
* [ ] New tests were added for isolated methods or new endpoints
* [ ] I opened an issue for any logical followups
* [ ] If this fixes a bug, "Fixes #XXX" is either the very first or very last line of the description.

## Before code review *and after additional commits* during review.

* [ ] Update title and description to account for additional changes
* [ ] All tests green
* [ ] Migrations were tested locally and do the right thing
* [ ] Booted up the branch locally, exercised any new code
* [ ] Percy changes are purposeful or explained
* [ ] Css changes are happy on mobile (via Percy is ok)

### CODE REVIEW

**Comment by sudara** [comment]
> Rollover states on any of these new buttons
image
Do you mean the new favorite / download button?

> by You by Artist logic
Should we just keep as is for now?

> what to do with the delete button on track edit
Are we changing track edit? Or you mean re: dark theme.

> add to favorites animation properly removed
Hmm, not sure what this means. Did we lose the animation? We definitely want to keep it in the button and should push back if there's a size problem.

> how to deal with groups of comments below a playlist track
How do you feel about keeping the style that exists now, with the arrow and I can put it on samo's list.

>  checkboxes are different sizes, site wide change?
My vote is we move to the new 16x16 everywhere.

>  consider new placements for edit playlist and edit descriptions buttons
The edit playlist has turned into "edit" right below the title. Do we need to still keep the button or can we remove it? I'm fine with temporarily hiding the "descriptions" one.

> color themes for external links
In track text? They should follow "static pages" styles.

**Comment by sudara** [comment]
One option is if you think the branch is in a stable-ish state, we can merge and add these items to a new issue.

**Comment by ofsound** [comment]
> Do you mean the new favorite / download button?

Yeah, specifically those, but other buttons on the Playlists designs aren't using components, the orangetone background used on Edit and post comment aren't the standard orange600 default button.

> > by You by Artist logic
> 
> Should we just keep as is for now?

I am happy without it saying 'By You' for now!

> > what to do with the delete button on track edit
> Are we changing track edit? Or you mean re: dark theme.

Because that section changed, it temporarily broke the layout of that Delete button. Just an opportunity to reconsider its placement. It's stable though, and sits like this:

Screenshot 2019-12-02 17 18 17

> > add to favorites animation properly removed 
> Hmm, not sure what this means. Did we lose the animation? We definitely want to keep it in the button and should push back if there's a size problem.

I wasn't sure if the animation was gonna shrink and stay in the button, but it's back in there now.

> > how to deal with groups of comments below a playlist track
> 
> How do you feel about keeping the style that exists now, with the arrow and I can put it on samo's list.

I re-added that upward triangle to just the Groups of comments on a single track view.

> 
> > checkboxes are different sizes, site wide change?
> 
> My vote is we move to the new 16x16 everywhere. Looks like it's mainly playlist edit and....

I made this change in forms.scss so it'll apply everywhere.

> > consider new placements for edit playlist and edit descriptions buttons
> 
> The edit playlist has turned into "edit" right below the title. Do we need to still keep the button or can we remove it? I'm fine with temporarily hiding the "descriptions" one.

I'm not a big fan of Edit Descriptions, so I removed it for now. That little button section no longer exists. Edit playlist happens up by the Title and Artist name.

> 
> > color themes for external links
> 
> In track text? They should follow "static pages" styles.

This was in relation to the External Links on the bottom of the Sidebar or in Cover View. They didn't exist in the latest Figma dark/white Playlist, but I roughed in some readable colors.

**Comment by sudara** [comment]
Maybe as a few final things:

* [ ] The whitespace above the single track "button bar" should be there regardless of whether a track has a description. Needs room to breathe...

0p1coast live at melatonin by carole | alonetone 2019-12-03 21-41-52

image

* [ ] We didn't schedule an artist name for the single track view. It's current position and text style has the side effect of making "metadata bar" look less clean. I think we should decide that the artist "belongs to" the title, move it a couple px closer to the h1 and use the spacing samo scheduled under the h1 for the space that's underneath the "title and author" group. Since it's already smaller text, maybe we can also make the author text color black? Basically, looking for a way to separate the title and metadata bar. Another option is to put the author as a piece of metadata like "Sudara uploaded on X" but that might deprioritize the author too much.

* [ ] I think download/favorite icons are sitting a px high? They are sorta itching at my #ppsense.

I'm going to add back to artist on the single track page...

**Comment by sudara** [comment]
* [ ] I think now is a good time to handle that "delete" debacle on edit track. I'd move the "save" button to it's expected location and "upgrade" it to the uhh.... "primary" button style (orange, bigger). And I'd move delete where "save" is now and it should be red ala the delete button on the new edit profile.

alonetone 2019-12-03 22-07-04

alonetone white theme 2019-12-03 22-09-14

**Comment by sudara** [comment]
Unfortunately I think we are "not done yet" with the "edit" button on playlist. All of our other edit buttons look different, I think we may need to add one in the same style, somewhere obvious. But I'm happy shipping this without that change for now, we can see how things go.

**Comment by ofsound** [comment]
> * [ ]  I think now is a good time to handle that "delete" debacle on edit track. I'd move the "save" button to it's expected location and "upgrade" it to the uhh.... "primary" button style (orange, bigger). And I'd move delete where "save" is now and it should be red ala the delete button on the new edit profile.
> 
> alonetone 2019-12-03 22-07-04
> 
> alonetone white theme 2019-12-03 22-09-14

@sudara I've moved the delete button, but it's broken mass_edit and some travis tests, because its in a new file now, assets/_edit instead of assets/edit?

**Comment by ofsound** [comment]
> Unfortunately I think we are not done yet with the "edit" button on playlist. All of our other edit buttons look different, I think we may need to add one in the same style, somewhere obvious. But I'm happy shipping this without that change for now, we can see how things go.

Perhaps it's a little flimsy as a small text link. The saga continues!

**Comment by sudara** [comment]
> I've moved the delete button, but it's broken mass_edit and some travis tests, because its in a new file now, assets/_edit instead of assets/edit?

I fixed the backend stuff on mass edit, except for one edge case: the case where an mp3 is missing will result in an error.

However, it looks like we lost our ajax_success feedback on mass edit in terms of frontend. All the stimulus stuff is still working.

**Comment by ofsound** [comment]
@sudara The Ajax feedback should be showing again on Mass Edit!

**Pull request merged**
