### PR TITLE
[WIP] Admin view

### PR DESCRIPTION
**Pull request by innatewonderer**
Did some research into existing admin gems.
`active_admin` seem to be flexible and sophisticated enough to meet some of our needs?

### CODE REVIEW

**Comment by innatewonderer** [comment]
Ignore this. Just testing my email notifications @innatewonderer

**Comment by kfox** [comment]
Tagging @innatewonderer as a test.

**Comment by innatewonderer** [comment]
Ignore this. Just testing my email notifications @innatewonderer

**Comment by sudara** [comment]
The admin stuff might be a good place to try out https://github.com/sudara/alonetone/issues/247

**Pull request closed without merging**
