### PR TITLE
Use correct a download syntax to download files.

### LINKED ISSUE #887: Clicking download button should download and not open in browser.
See https://alonetone.com/discuss/posts/488

`Content-Disposition: attachment;` is our friend

but this is a modern way to accomplish:

`<a download="blah.mp3" href="aaoetuh/aoeuth">some link</a>`

Just not sure if that works with redirects....

### PR DESCRIPTION
**Pull request by innatewonderer**
Fixes #887 

I'm seeing `filename delegated to attachment, but attachment is nil` on assets/show.
Action_Controller__Exception_caught

## "Ready For Review" checklist

These checklists are to help ensure the code review basics are covered. Consider removing to reduce noise.

* [ ] PR title accurately summarizes changes
* [ ] New tests were added for isolated methods or new endpoints
* [ ] I opened an issue for any logical followups
* [ ] If this fixes a bug, "Fixes #XXX" is either the very first or very last line of the description.

## Before code review *and after additional commits* during review.

* [ ] Update title and description to account for additional changes
* [ ] All tests green
* [ ] Booted up the branch locally, exercised any new code
* [ ] Percy changes are purposeful or explained
* [ ] Css changes are happy on mobile (via Percy is ok)

### CODE REVIEW

**Comment by innatewonderer** [comment]
@sudara Am I correct in assuming we want the `mp3_file_name` to be provided as download name  Per comment [here](https://github.com/sudara/alonetone/blob/master/app/models/asset.rb#L73) it's been depricated? So we cannot rely on that column at all? (any plans on removing those columns in the future, or do we still need them?)
```
  # @deprecated Please use asset.audio_file.filename.
  def mp3_file_name
    if filename = audio_file&.filename
      filename.to_s
    end
  end
```
I'm still researching on a way to work with `has_one_attached :audio_file` locally if the file is missing. If you have any ideas, it'd be greatly appreciated.

**Comment by sudara** [comment]
@innatewonderer Have you migrated to using the seeds yet? Manfred spent a lot of work getting everything very shiny on the new seeds, including support for downloads, etc. There's more work to be done on #837 

#890 is the same error as you seem to be getting locally. It's on Manfred's radar for next week.  

Are you constantly seeing that error on all assets? Does the download attribute work btw?

**Comment by sudara** [comment]
More info on seeds just in case: https://alonetone.slack.com/archives/C03E2AE6J/p1569946263009700

**Comment by sudara** [comment]
#898 and #899 were merged which may alleviate your error. But refreshing the alonetone.yml and using the seeds is the endgame...it's possible whatever your local config is pointing to just isn't there anymore.

**Comment by innatewonderer** [comment]
I did update my `alonetone.yml` based on that original comment but keep forgetting to migrate to seeds (granted, it has been useful in my recent work on figuring out counter discrepancies :) But this kind of work is def more clear with seeds).

**Comment by innatewonderer** [comment]
> Does the download attribute work btw?

It works beautifully.

**Comment by innatewonderer** [comment]
> #890 is the same error as you seem to be getting locally — It's on Manfred's radar for next week. Are you constantly seeing that error on all assets? 

It does NOT fail when used with seed data.
It does, however, occur when running with snapshot data on all records that I didn't actually upload manually. So if there is no actual file in storage associated with the record. (I do often upload files locally to test various functionality, so those assets work just fine with new download attr).

**Comment by sudara** [comment]
> with snapshot data on all records that I didn't actually upload manually. 

That makes sense, as you don't have access to production s3 keys I guess. 

Glad you got seeds sorted!

One question: what browsers did you test the download attribute on?

**Pull request merged**
