### PR TITLE
Fix Playlist external links

### LINKED ISSUE #587: Playlist Track View often shows 2 "website links" with no links and wrong icon
Cables  by Len Sasso 2019-05-13 20-54-03

### PR DESCRIPTION
**Pull request by sudara**
Fixes #587 

We've been seeing fake links to "website" on playlists. This bug/bad view logic has been haunting us for too long.

* [x] Fixes bug
* [x] Adds "external links" to the playlist that percy renders
* [x] Add support for bandcamp
* [x] Add support for youtube

## "Ready For Review" checklist

* [x] PR title accurately summarizes changes
* [x] PR description
  * Does this fix any open issues?
  * What changes are you making?
  * Why did you implement it this way?
  * Is there anything reviewers need to know or pay attention to?
  * Does anything special need to happen for deployment?
* [ ] Optional: Inline github PR comments explaining context of tricky / complicated / unexpected lines so reviewers can follow along.
* [x] If appropriate, new tests were added for isolated methods or new endpoints
* [ ] All tests green
* [x] Percy changes are purposeful or explained
* [x] I booted up the branch locally, exercised any new code I wrote.
* [ ] If css was touched, I verified changes are happy on mobile (via Percy is ok)
* [ ] I opened an issue for any logical followups

### CODE REVIEW

**Comment by sudara** [comment]
@ofsound can you look into issue here where google play is the default "website" logo? Also, would be sweet to add bandcamp and youtube, i'm not sure if either of those are in figma...

**Comment by ofsound** [comment]
@sudara I've added bandcamp and youtube icon capabilities to these external playlist links. I think they should have some of the same logic as our User external links. Where if its a bandcamp url, it adds class="bandcamp" to the <a> and maybe says "Bandcamp" instead of "Website" in the link text.

**Comment by sudara** [comment]
@ofsound Would you mind touching up the css for text alignment here? Looks like it needs to go down a px or two and prob needs to hug the logo by px, maybe 

Messages Image(238308848)

**Comment by ofsound** [comment]
> @ofsound Would you mind touching up the css for text alignment here? Looks like text needs to go down a px or two and prob needs to hug the logo by a px or two, just so they are better logically grouped.

I've done it!

**Pull request merged**
